<?php

namespace backend\models;

use common\vendor\AppConstants;
use common\vendor\AppLabels;

/**
 * This is the model class for table "ppa_month".
 *
 * @property integer $id
 * @property integer $ppa_setup_permit_id
 * @property integer $ppam_month
 * @property integer $ppam_year
 * @property string $ppam_cert_number
 * @property integer $created_by
 * @property integer $created_at
 * @property integer $updated_by
 * @property integer $updated_at
 *
 * @property PpaSetupPermit $ppaSetupPermit
 * @property AttachmentOwner $attachmentOwner
 */
class PpaMonth extends AppModel {
    
    public $month_label;
    
    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'ppa_month';
    }
    
    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['ppa_setup_permit_id', 'ppam_month', 'ppam_year'], 'required', 'message' => AppConstants::VALIDATE_REQUIRED],
            [['ppa_setup_permit_id', 'ppam_month', 'ppam_year'], 'integer', 'message' => AppConstants::VALIDATE_INTEGER],
            [['ppam_cert_number'], 'string', 'max' => 4],
            [['ppa_setup_permit_id'], 'exist', 'skipOnError' => true, 'targetClass' => PpaSetupPermit::className(), 'targetAttribute' => ['ppa_setup_permit_id' => 'id']],
        ];
    }
    
    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'ppa_setup_permit_id' => AppLabels::SETUP_POINT_PERMIT,
            'ppam_month' => AppLabels::MONTH,
            'ppam_year' => AppLabels::YEAR,
            'ppam_cert_number' => AppLabels::CERTIFIED_NUMBER,
        ];
    }
    
    public function afterFind() {
        parent::afterFind(); // TODO: Change the autogenerated stub
        
        $dt = new \DateTime();
        $dt->setDate($this->ppam_year, $this->ppam_month, 1);
        $this->month_label = $dt->format('M Y');
        
        return true;
    }

    public function beforeDelete()
    {
        $attachment = $this->attachmentOwner;
        if(!is_null($attachment)){
            $attachment = $attachment->attachment;
        }
        if(!is_null($attachment)){
            $attachment->delete();
        }
        return parent::beforeDelete();
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPpaSetupPermit() {
        return $this->hasOne(PpaSetupPermit::className(), ['id' => 'ppa_setup_permit_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAttachmentOwner() {
        return $this->hasOne(AttachmentOwner::className(), ['atfo_module_pk' => 'id'])->andOnCondition(['atfo_module_code' => AppConstants::MODULE_CODE_PPA_SETUP_PERMIT_CERT_NUMB]);
    }
}
